presciptions:
  cache:
    ttl: 60
    heap-size: 100

---
spring:
  profiles: default
eureka:
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://tracing-server:9411
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/


chaos:
    monkey:
        enabled: true
        watcher:
            service: true
management:
    endpoint:
        chaosmonkey:
            enabled: true
        chaosmonkeyjmx:
            enabled: true
    endpoints:
        web:
            base-path: /actuator
            exposure:
                include: '*'
